[package]
name = "signature-verifier-api"
version = "1.0.0"
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"
edition = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }
client = { workspace = true }

[lints]
workspace = true
