[package]
name = "signature-verifier-api"
version = "0.1.0"
rust-version = { workspace = true }
edition = "2021"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
