[package]
name = "report"
version = "1.0.0"
rust-version = { workspace = true }
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { workspace = true }
eyre = "0.6.8"
itertools = { workspace = true }
thiserror = { workspace = true }
valuable = { version = "0.1.0", features = ["derive"] }

[lints]
workspace = true
