[package]
name = "ampd-sdk"
version = "0.1.0"
rust-version = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = "0.1.59"
error-stack = { workspace = true }
events = { workspace = true }
mockall = { workspace = true }
futures = "0.3.25"
prost = "0.13.5"
prost-types = "0.13.5"
thiserror = { workspace = true }
tonic = "0.13.0"
tendermint = "0.35.0"
serde_json = { workspace = true }

[build-dependencies]
tonic-build = "0.13.0"

[lints]
workspace = true
