[package]
name = "ampd-sdk"
version = "0.1.0"
rust-version = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = "0.1.59"
error-stack = { workspace = true }
mockall = { workspace = true }
prost = "0.13.5"
prost-types = "0.13.5"
tonic = "0.13.0"

[build-dependencies]
tonic-build = "0.13.0"

[lints]
workspace = true
