[package]
name = "ampd-sdk"
version = "0.1.0"
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"
edition = { workspace = true }

[dependencies]
ampd = { path = "../../ampd", default-features = false, features = ["url"] }
ampd-proto = { workspace = true }
async-trait = { workspace = true }
axelar-wasm-std = { workspace = true }
config = { workspace = true }
cosmrs = { workspace = true }
error-stack = { workspace = true }
events = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
humantime-serde = { workspace = true }
mockall = { workspace = true }
report = { workspace = true }
serde = { workspace = true }
serde-aux = "4.7.0"
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = "0.13.0"
tracing = { workspace = true }
typed-builder = { workspace = true }
valuable = { workspace = true }

[build-dependencies]

[dev-dependencies]
temp-env = "0.3.6"
tempfile = "3.21.0"
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
