[package]
name = "evm-gateway"
version = "0.1.0"
rust-version = { workspace = true }
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axelar-wasm-std = { workspace = true }
cosmwasm-std = { workspace = true }
ethers = { version = "2.0.14", features = ["abigen"] }
k256 = { version = "0.13.1", features = ["ecdsa"] }
multisig = { workspace = true }
sha3 ={ workspace = true }
thiserror = { workspace = true }

[build-dependencies]
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
zip = "2.0.0"

[lints]
workspace = true
