[package]
name = "sui-gateway"
version = "1.0.0"
edition = { workspace = true }
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"

[dependencies]
bcs = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
hex = { workspace = true }
multisig = { workspace = true, features = ["library"] }
router-api = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
sui-types = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
bs58 = { workspace = true }
rand = { workspace = true }
