[package]
name = "events-derive"
version = "1.0.0"
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dev-dependencies]
events = { workspace = true }

[dependencies]
error-stack = { workspace = true }
quote = { workspace = true }
serde = "1.0.183"
serde_json = "1.0.105"
syn = { workspace = true }

[lints]
workspace = true
