[package]
name = "xrpl-types"
version = "1.0.0"
rust-version = { workspace = true }
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axelar-wasm-std = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
error-stack = { workspace = true }
k256 = { version = "0.13.1", features = ["ecdsa"] }
multisig = { workspace = true }
router-api = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
bs58 = "0.5.0"
cw-storage-plus = { workspace = true }
ripemd = "0.1.3"
sha2 = { version = "0.10.7" }
interchain-token-service = { workspace = true, features = ["library"] }
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
serde_json = "1.0.89"
regex = "1.11.1"
lazy_static = "1.5.0"

[lints]
workspace = true
