[package]
name = "gateway-api"
version = "1.0.0"
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axelar-wasm-std = { workspace = true }
client = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
msgs-derive = { workspace = true }
router-api = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
goldie = { workspace = true }

[lints]
workspace = true
