[package]
name = "gateway-api"
version = "0.1.0"
rust-version = { workspace = true }
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = { workspace = true }
router-api = { workspace = true }

[lints]
workspace = true
