[package]
name = "stellar"
version = "1.0.0"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
axelar-wasm-std = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
hex = "0.4.3"
multisig = { workspace = true, features = ["library"] }
router-api = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
stellar-strkey =  { version = "0.0.8" }
stellar-xdr = { version = "21.2.0" }
thiserror = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
goldie = { workspace = true }
rand = "0.8.5"
