[package]
name = "router-api"
version = "1.0.0"
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axelar-wasm-std = { workspace = true, features = ["derive"] }
client = { workspace = true }
const-str = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
error-stack = { workspace = true }
flagset = { version = "0.4.3", features = ["serde"] }
msgs-derive = { workspace = true }
report = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
valuable = "0.1.0"

[dev-dependencies]
goldie = { workspace = true }
hex = "0.4.3"
rand = { workspace = true }

[lints]
workspace = true
