[package]
name = "axelar-wasm-std-derive"
version = "1.0.0"
rust-version = { workspace = true }
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
error-stack = { workspace = true }
quote = { workspace = true }
report = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }
cosmwasm-std = { workspace = true }

[dev-dependencies]
axelar-wasm-std = { workspace = true }

[lints]
workspace = true
