name: ampd-handlers -  Build and release binary and image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Github handler tag to release binaries for (e.g., evm-handler-v1.0.0, sui-handler-v1.0.0)
        required: true
      dry-run:
        description: Run in dry-run mode (set to false to actually release)
        required: true
        default: 'true'

jobs:
  extract-semver:
    runs-on: ubuntu-22.04
    name: Validate tag and extract semver
    permissions:
      contents: write
      packages: write
      id-token: write
    outputs:
      semver: ${{ steps.extract_semver.outputs.semver }}
      version: ${{ steps.extract_semver.outputs.version }}
      handler: ${{ steps.extract_semver.outputs.handler }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ghwf-${{ github.event.repository.name }}

      - name: Extract semver and handler from tag
        id: extract_semver
        run: |
          tag="${{ github.event.inputs.tag }}"
          handler=$(echo "$tag" | sed -E 's/-handler-v.*//')
          full_semver=$(echo "$tag" | sed -E 's/.*-handler-(v.*)/\1/')
          version_number=$(echo "$full_semver" | sed 's/^v//')
          
          if [ -z "$handler" ] || [ -z "$full_semver" ]; then
            echo "Error: Failed to extract handler or semver from tag: $tag"
            exit 1
          fi
          
          echo "handler=$handler" >> $GITHUB_OUTPUT
          echo "semver=$full_semver" >> $GITHUB_OUTPUT
          echo "version=$version_number" >> $GITHUB_OUTPUT

      - name: Validate tag
        env:
          TAG: ${{ github.event.inputs.tag }}
          HANDLER: ${{ steps.extract_semver.outputs.handler }}
          SEMVER: ${{ steps.extract_semver.outputs.semver }}
        run: |
          if [[ ! $TAG =~ ^[a-z]+-handler-v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then
            echo "invalid tag format. Expected: {handler}-handler-vX.Y.Z"
            exit 1
          fi
          echo "Tag is okay"
          if aws s3 ls s3://axelar-releases/ampd-handlers/"$HANDLER"/"$SEMVER"/ | grep -q .; then
            echo "tag already exists, use a new one"
            exit 1
          fi

  release-binaries:
    runs-on: ubuntu-22.04
    needs: extract-semver
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ghwf-${{ github.event.repository.name }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: '0'
          ref: ${{ github.event.inputs.tag }}
          submodules: recursive

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: "cache-release-ubuntu-22.04-amd64"

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install protoc
        uses: arduino/setup-protoc@a8b67ba40b37d35169e222f3bb352603327985b6 # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build and sign linux binary
        env:
          SEMVER: ${{ needs.extract-semver.outputs.semver }}
          HANDLER: ${{ needs.extract-semver.outputs.handler }}
        run: |
          OS="linux"
          ARCH="amd64"

          cargo build --release --bin ${HANDLER}-handler
          if [ $? -ne 0 ]; then
            echo "Error: cargo build failed"
            exit 1
          fi
          
          mkdir handlerbin
          mv "/home/runner/work/axelar-amplifier/axelar-amplifier/target/release/${HANDLER}-handler" "./handlerbin/${HANDLER}-handler-$OS-$ARCH-$SEMVER"

          gpg --armor --detach-sign "./handlerbin/${HANDLER}-handler-$OS-$ARCH-$SEMVER"

      - name: Test Binary Format
        working-directory: ./handlerbin
        env:
          HANDLER: ${{ needs.extract-semver.outputs.handler }}
        run: |
          for binary in ./${HANDLER}-handler-*; do
          if [[ "$binary" != *.asc ]]; then
            echo "Testing binary: $binary"
            OUTPUT=$(file "$binary" | cut -d: -f2- | awk -F, '{print $1"," $2}')
            EXPECTED="ELF 64-bit LSB pie executable, x86-64"

            echo "Output: $OUTPUT"
            echo "Expected: $EXPECTED"

            if [[ "$OUTPUT" == *"$EXPECTED"* ]]; then
              echo "The binary format is correct."
            else
              echo "Error: The binary format does not match the expected format."
              exit 1
            fi
          fi
          done

      - name: Create zip and sha256 files
        working-directory: ./handlerbin
        run: |
          for i in `ls | grep -v .asc`
          do
            shasum -a 256 $i | awk '{print $1}' > $i.sha256
            zip $i.zip $i
          done

      - name: Upload binaries to release
        if: github.event.inputs.dry-run == 'false'
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./handlerbin/*
          tag: ${{ github.event.inputs.tag }}
          overwrite: true
          file_glob: true

      - name: Upload binaries to S3
        if: github.event.inputs.dry-run == 'false'
        env:
          HANDLER: ${{ needs.extract-semver.outputs.handler }}
          SEMVER: ${{ needs.extract-semver.outputs.semver }}
          S3_PATH: s3://axelar-releases/ampd-handlers/${{ needs.extract-semver.outputs.handler }}/${{ needs.extract-semver.outputs.semver }}
        run: |
          aws s3 cp ./handlerbin ${S3_PATH}/ --recursive

      - name: Prepare source directory structure for R2 upload
        id: prepare-r2-release
        env:
          HANDLER: ${{ needs.extract-semver.outputs.handler }}
        run: |
          version="${{ needs.extract-semver.outputs.version }}"
          mkdir -p "./${version}"
          cp -R ./handlerbin/. "./${version}/"
          echo "release-dir=./${version}" >> $GITHUB_OUTPUT
          echo "r2-destination-dir=./releases/ampd-handlers/${HANDLER}" >> $GITHUB_OUTPUT

      - name: Upload to R2
        if: github.event.inputs.dry-run == 'false'
        uses: ryand56/r2-upload-action@31453780fdaaf43c8eff7231dd521f8669b48621 # v1.3.2
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CF }}
          r2-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CF }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ${{ steps.prepare-r2-release.outputs.release-dir }}
          destination-dir: ${{ steps.prepare-r2-release.outputs.r2-destination-dir }}

  release-docker:
    runs-on: ubuntu-22.04
    needs: extract-semver
    permissions:
      contents: write
      packages: write
      id-token: write
    if: github.event.inputs.dry-run == 'false'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: '0'
          ref: ${{ github.event.inputs.tag }}
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push docker image
        env:
          PLATFORM: linux/amd64
          SEMVER: ${{ needs.extract-semver.outputs.semver }}
          HANDLER: ${{ needs.extract-semver.outputs.handler }}
        run: |
          DOCKER_BUILDKIT=1 docker buildx build \
            --platform ${PLATFORM} \
            --output "type=image,push=true" \
            --build-arg HANDLER=${HANDLER} \
            -f ampd-handlers/Dockerfile \
            -t axelarnet/axelar-ampd-${HANDLER}-handler-linux-amd64:${SEMVER} --provenance=false .

  combine-sign:
    needs: [ release-docker, extract-semver ]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
      id-token: write
    if: github.event.inputs.dry-run == 'false'
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@9614fae9e5c5eddabb09f90a270fcb487c9f7149 # 3.3.0
        with:
          cosign-release: 'v2.2.2'

      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create multiarch manifest
        env:
          SEMVER: ${{ needs.extract-semver.outputs.semver }}
          HANDLER: ${{ needs.extract-semver.outputs.handler }}
        run: |
          docker buildx imagetools create -t axelarnet/axelar-ampd-${HANDLER}-handler:${SEMVER} \
            axelarnet/axelar-ampd-${HANDLER}-handler-linux-amd64:${SEMVER}

      - name: Sign the images with GitHub OIDC
        run: cosign sign -y --oidc-issuer https://token.actions.githubusercontent.com ${TAGS}
        env:
          TAGS: axelarnet/axelar-ampd-${{ needs.extract-semver.outputs.handler }}-handler:${{ needs.extract-semver.outputs.semver }}
          COSIGN_EXPERIMENTAL: 1
